### PR TITLE
Alternative way to get form data

### PR DESCRIPTION
**Pull request by shincoder**

### CODE REVIEW

**Comment by laracasts** [comment]
I don't think that would work. That's the original data, not the current.

**Comment by shincoder** [comment]
We are not fetching data from originalData, just properties. this[prop] is the one fetching data from the form.

Tested!

**Comment by laracasts** [comment]
Oh I see. Yeah, that's fine. 

Going to keep as is, since this should reflect the source code for the video.

**Comment by shincoder** [comment]
Nice. And thanks for the great content Jeffrey.

**Pull request closed without merging**
